select  {{ dbt_utils.generate_surrogate_key(['customer_id']) }} as customer_key,
        customer_id,
        first_name,
        last_name,
        email,
        phone_number,
        date_of_birth,
        gender,
        country,
        state,
        city,
        address,
        customer_status,
        created_at,
        updated_at
from {{ ref('(silver_transactions)') }}