sources:
  - name: finflow_bronze_src
    database: FINFLOW_DB
    schema: FINFLOW_BRONZE
    loader: Bronze Layer Snowflake

    tables:
      - name: bronze_customers
        description: This shows the details of the customer. One row per customer.

        columns:
          - name: customer_id
            description: The unique identifier of each customer.

          - name: first_name
            description: First name of each customer.

          - name: last_name
            description: The last name of each customer.

          - name: email
            description: Email of each customer

          - name: phone_number
            description: The phone number of each customer

          - name: date_of_birth
            description: Date of birth of a customer

          - name: gender
            description: Gender of each customer

          - name: country
            description: Full country name of each customer

          - name: state
            description: Full state name of each customer

          - name: city
            description: City of each customer

          - name: address
            description: Address where each customer lives

          - name: customer_status
            description: The activity status of each customer

          - name: created_at
            description: The account creation date of each customer

          - name: updated_at
            description: The date when a customer details were updated


      - name: bronze_accounts
        description: >
          The details of each customer account. Every customer must have an account.
          
        columns:
          - name: account_id
            description: The unique identifier of each account.

          - name: customer_id
            description: >
              Each customer owns an account. This uniquely identifies the owner of each account.

          - name: account_number
            description: The account number of each account.

          - name: account_type
            description: The account type of each account.

          - name: currency
            description: The currency which the account operates on. 

          - name: balance
            description: The balance one each account.

          - name: account_status
            description: The state of each customers account.

          - name: opened_at
            description: The date each account was opened.

          - name: closed_at
            description: The date each account was closed.

      
      - name: bronze_beneficiaries
        description: Details of each customers beneficiaries

        columns:
          - name: beneficiary_id
            description: This identifies each beneficiaries uniquely.

          - name: customer_id
            description: Each customer that has a beneficiary.

          - name: beneficiary_name
            description: The name of each beneficiary.
            
          - name: beneficiary_account
            description: The account number of each beneficiary.
          
          - name: bank_name
            description: The bank name of each beneficiary.

          - name: status
            description: The state of each beneficiary account.

          - name: created_at
            description: The date when a customer saved an account as a beneficiary.


      - name: bronze_transactions
        description: Stores all the transaction movement.

        columns:
          - name: transaction_id
            description: Unique identifier of each transaction.

          - name: account_id
            description: The identifier of each account that initiated the transaction.

          - name: transaction_reference
            description: The reference ID for each transaction.

          - name: transaction_type
            description: Describes the type of each transaction that occured.

          - name: transaction_status
            description: Describes the present state of each transaction that occured.

          - name: transaction_direction
            description: >
              Shows the direction of each transaction. Whether it's a debit or a credit.

          - name: amount
            description: The transaction amount.

          - name: currency
            description: The transaction currency. Default is NGN.

          - name: transaction_channel
            description: >
              This describes how each transaction happened. Whether it's a bank transfer, POS, WEB etc.

          - name: description
            description: The purpose of the transaction.

          - name: original_transaction_id
            description: >
              This ID indicates that the transaction type is a reversed type. 
              It references the transaction id column that the transaction was initiated from.

          - name: fee_for_transaction_id
            description: >
              ID of transactions that have it's fees debited. This reference the transaction id. 
              The transaction type is a FEE and the transaction direction is always debit.
          
          - name: transaction_at
            description: Timestamp which tells us when each transaction event happened. 

          - name: created_at
            description: >
              Timestamp which tells us when each transaction record was inserted into the operational database.


      - name: bronze_transfers
        description: Transfers simply stores information about transactions to a beneficiary or a finflow account.

        columns:
          - name: transfer_id
            description: Unique identifier for each transfers

          - name: transfer_reference
            description: Records the transfer reference number.

          - name: sender_transaction_id
            description: >
              The unique identifier of the sender that initiated the transfer. References the transaction id in the transactions table.

          - name: receiver_transaction_id
            description: The id of the receiever of the transfer.

          - name: beneficiary_id
            description: The beneficiary id that receives the transfer. References the beneficiaries table.

          - name: transfer_method
            description: >
              This describes the method of each transfer. 
              Whether its a bank transfer or an internal transfer - when both accounts are FinFlow account.

          - name: transfer_purpose
            description: The purpose of each transfer.

          - name: created_at
            description: Timestamp when each transfer was initiated.


      - name: bronze_cards
        description: The details of each customers card information.

        columns:
          - name: card_id
            description: The unique identifier of each card.

          - name: customer_id
            description: The customer id which each card belongs to.

          - name: account_id
            description: The account id which each card belongs to.

          - name: card_number
            description: Unique 16 digit number that is accoustomed to each card.

          - name: card_type
            description: The type of card issued.

          - name: card_status
            description: The state of the card.

          - name: issued_at
            description: Timestamp of when the card was issued.

          - name: expires_at
            description: Expiration date of card.

      - name: bronze_card_transactions
        description: Details of transactions initiated and done using cards.

        columns:
          - name: card_transaction_id
            description: Unique Identifier that captures card transactions.

          - name: card_id
            description: Unique identifier for each card. References card_id in the cards table.

          - name: transaction_id
            description: Unique identifier for each transaction. References transaction_id in the transactions table.

          - name: merchant_name
            description: The type of business that card transactions was done on.

          - name: merchant_category
            description: The category where the business falls in.

          - name: transaction_at
            description: The timestamp the card transactions was initiated.

          - name: created_at
            description: Timestamp when the record was entered in the database.


      - name: bronze_loans
        description: Information about the loans disbursed.

        columns:
          - name: loan_id
            description: Unique identifier for each loan.

          - name: customer_id
            description: The customer id the loan was given to.

          - name: account_id
            description: The account id the loan was sent to.

          - name: loan_reference
            description: The reference number of the loan.

          - name: loan_type
            description: Describes the purpose for the loan.

          - name: loan_status
            description: The state of the loan disbursed.

          - name: principal_amount
            description: The original amount of the loan.

          - name: interest_rate
            description: The interest fee accumulated via the laon.

          - name: total_repayable_amount
            description: This is the total amount repayable. 

          - name: outstanding_balance
            description: holder

          - name: term_months
            description: Number of months the loan can stay before payment.

          - name: approved_at
            description: Date and time the loan ws approved.

          - name: disbursed_at
            description: The date the loan was disbursed to the account.

          - name: maturity_date
            description: The date the lifeline of the loan will be terminated.

          - name: created_at
            description: The date and time the loan was initiated.

      
      - name: bronze_loan_payments
        description: Details of the loan payments made.

        columns: 
          - name: loan_payment_id
            description: Unique identifier for each loan payment.

          - name: loan_id
            description: The unique identifier for each loan. References the loan_id on the loans table.

          - name: transaction_id
            description: Unique identifier for each loan transaction recorded in the transactions table.

          - name: payment_reference
            description: Loan payment reference.

          - name: payment_amount
            description: The full loan amount repayable.

          - name: principal_amount
            description: Initial loan amount disbursed.

          - name: interest_amount
            description: Payable Interests for each loans.

          - name: payment_status
            description: State of each loan.

          - name: payment_at
            description: Date and time each loan was paid.

          - name: created_at
            description: Date and time each records was entered in the database.
        


     